"""empty message

Revision ID: 047858c06b09
Revises: ea2dcd22a14b
Create Date: 2024-06-06 21:58:25.624687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047858c06b09'
down_revision = 'ea2dcd22a14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.alter_column('hubspot_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('hubspot_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('hubspot_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.alter_column('hubspot_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
