"""empty message

Revision ID: 0d1b1e92c338
Revises: 4aa983cd52c1
Create Date: 2024-06-23 20:11:07.139843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1b1e92c338'
down_revision = '4aa983cd52c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_deal_stages', schema=None) as batch_op:
        batch_op.drop_constraint('student_deal_stages_hubspot_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_deal_stages', schema=None) as batch_op:
        batch_op.create_unique_constraint('student_deal_stages_hubspot_id_key', ['hubspot_id'])

    # ### end Alembic commands ###
