"""empty message

Revision ID: 1663d24b4c12
Revises: f7b7090959f0
Create Date: 2024-06-23 17:47:17.416965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1663d24b4c12'
down_revision = 'f7b7090959f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.drop_column('smart_matcher_notification')
        batch_op.drop_column('student_affiliation_project')
        batch_op.drop_column('languages_fluency')
        batch_op.drop_column('student_firstname')
        batch_op.drop_column('student_email')
        batch_op.drop_column('student_cv_link')
        batch_op.drop_column('student_linkedin_link')
        batch_op.drop_column('student_lastname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_lastname', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('student_linkedin_link', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_cv_link', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_email', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('student_firstname', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('languages_fluency', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_affiliation_project', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('smart_matcher_notification', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
