"""empty message

Revision ID: 1d4e1f7d26f4
Revises: 6dfd2cb8bef9
Create Date: 2024-07-21 20:19:44.783380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d4e1f7d26f4'
down_revision = '6dfd2cb8bef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp_tmp_hshubspot_contacts_updated_c811_a85')
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.alter_column('student_country',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.alter_column('student_country',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.create_table('tmp_tmp_hshubspot_contacts_updated_c811_a85',
    sa.Column('json_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
