"""empty message

Revision ID: 26e2ef8095e4
Revises: 5c793c104c45
Create Date: 2024-06-27 00:15:17.310540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e2ef8095e4'
down_revision = '5c793c104c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csa_hubspot_id', sa.String(), nullable=True))
        batch_op.drop_column('csv_hubspot_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csv_hubspot_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('csa_hubspot_id')

    # ### end Alembic commands ###
