"""empty message

Revision ID: 2779ebd3c38c
Revises: ceab62691071
Create Date: 2024-07-24 09:38:06.819530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2779ebd3c38c'
down_revision = 'ceab62691071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pulse_table_test', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__11d87396')

    op.drop_table('pulse_table_test')
    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__c4109d3e')

    with op.batch_alter_table('student_new_payment', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.create_unique_constraint(None, ['hubspot_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_new_payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__c4109d3e', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    op.create_table('pulse_table_test',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('job_ready_students', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('active_job_searchers', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('daily_applications', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('interview_process_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('students_with_interview_process', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('daily_callbacks', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('this_month_callbacks', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('cummulative_monthly_applications', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('cvr_callback_to_applications', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('daily_placements', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('monthly_cummulative_placements', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('yearly_cummulative_placements', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('cvr_placement_to_callback', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('placement_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('monthly_placements_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('yearly_placements_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quarterly_cummulative_placements', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('quarterly_placements_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    with op.batch_alter_table('pulse_table_test', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__11d87396', ['date'], unique=False)

    # ### end Alembic commands ###
