"""empty message

Revision ID: 284ff962881b
Revises: 29c58998f66f
Create Date: 2024-07-17 13:32:31.958021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284ff962881b'
down_revision = '29c58998f66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_stage', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.drop_column('deal_stage')

    # ### end Alembic commands ###
