"""empty message

Revision ID: 288f8a0469fd
Revises: c74343aa6bee
Create Date: 2024-07-01 21:10:54.211054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288f8a0469fd'
down_revision = 'c74343aa6bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('job_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_description', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
