"""empty message

Revision ID: 2a1b2b6a9832
Revises: 7715ae76d0e0
Create Date: 2024-06-05 10:59:58.913534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a1b2b6a9832'
down_revision = '7715ae76d0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_ms_id', sa.String(), nullable=True))
        batch_op.drop_constraint('job_ready_students_masterschool_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['student_ms_id'])
        batch_op.drop_column('masterschool_id')

    with op.batch_alter_table('mock_interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_id', sa.String(), nullable=False))
        batch_op.alter_column('mock_interview_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_foreign_key(None, 'processes', ['process_id'], ['id'])

    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_ms_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('student_ms_id')

    with op.batch_alter_table('mock_interviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('mock_interview_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('process_id')

    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('masterschool_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('job_ready_students_masterschool_id_key', ['masterschool_id'])
        batch_op.drop_column('student_ms_id')

    # ### end Alembic commands ###
