"""empty message

Revision ID: 304d063bbf1c
Revises: dac733e3d51f
Create Date: 2024-08-01 14:42:54.824665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304d063bbf1c'
down_revision = 'dac733e3d51f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bg_students_ms_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hubspot_id', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'bg_students', ['hubspot_id'], ['hubspot_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bg_students_ms_score', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hubspot_id')

    # ### end Alembic commands ###
