"""empty message

Revision ID: 331ec2b52f22
Revises: 304d063bbf1c
Create Date: 2024-08-01 15:07:13.055252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331ec2b52f22'
down_revision = '304d063bbf1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bg_students_ms_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corrected_date_of_review', sa.Date(), nullable=False))
        batch_op.alter_column('date_of_review',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bg_students_ms_score', schema=None) as batch_op:
        batch_op.alter_column('date_of_review',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('corrected_date_of_review')

    # ### end Alembic commands ###
