"""empty message

Revision ID: 33f07ec796a3
Revises: d05cfcb1303f
Create Date: 2024-07-25 19:18:46.185085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f07ec796a3'
down_revision = 'd05cfcb1303f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_test_table', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__870319ef')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__0d3ec9c0')

    with op.batch_alter_table('student_deal_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_if_rel', sa.String(), nullable=True))

    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__bc342da5')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__bc342da5', ['date'], unique=False)

    with op.batch_alter_table('student_deal_stages', schema=None) as batch_op:
        batch_op.drop_column('company_if_rel')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__0d3ec9c0', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('new_test_table', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__870319ef', ['hubspot_id', 'type_of_collection_code', 'created_at'], unique=False)

    # ### end Alembic commands ###
