"""empty message

Revision ID: 3671c872dd17
Revises: 2ff0ea33de02
Create Date: 2024-07-17 09:46:01.771405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3671c872dd17'
down_revision = '2ff0ea33de02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('domain',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('domain',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
