"""empty message

Revision ID: 39866518020a
Revises: 671112d13228
Create Date: 2024-07-29 12:57:28.591346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39866518020a'
down_revision = '671112d13228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__0b076f72')

    with op.batch_alter_table('bg_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hs_pipeline', sa.String(), nullable=True))

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__7f0a4eb9')

    with op.batch_alter_table('student_new_payment', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index('idx_rivery__0b501c12')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_new_payment', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__0b501c12', ['id', 'hubspot_id'], unique=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__7f0a4eb9', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('bg_students', schema=None) as batch_op:
        batch_op.drop_column('hs_pipeline')

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__0b076f72', ['hubspot_id', 'type_of_collection_code', 'created_at'], unique=False)

    # ### end Alembic commands ###
