"""empty message

Revision ID: 4606f253e822
Revises: 4b3e6108c2c5
Create Date: 2024-07-22 14:00:13.132903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4606f253e822'
down_revision = '4b3e6108c2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.alter_column('type_of_stage',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.alter_column('type_of_stage',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
