"""empty message

Revision ID: 462f23a702e3
Revises: f79beb2f13fc
Create Date: 2024-07-29 10:38:17.287911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462f23a702e3'
down_revision = 'f79beb2f13fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__672c71a3')

    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hubspot_deal_id', sa.String(), nullable=True))

    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hubspot_deal_id', sa.String(), nullable=True))

    with op.batch_alter_table('student_new_payment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('type_of_collection',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index('idx_rivery__362a5885')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_new_payment', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__362a5885', ['id', 'hubspot_id'], unique=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('type_of_collection',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('hubspot_deal_id')

    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.drop_column('hubspot_deal_id')

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__672c71a3', ['hubspot_id', 'type_of_collection_code', 'created_at'], unique=False)

    # ### end Alembic commands ###
