"""empty message

Revision ID: 48ac1a85d996
Revises: 2a1b2b6a9832
Create Date: 2024-06-06 19:57:11.133265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ac1a85d996'
down_revision = '2a1b2b6a9832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sa.String(), nullable=False))

    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_secured_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('job_secured_date')

    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.drop_column('domain')

    # ### end Alembic commands ###
