"""empty message

Revision ID: 4aa983cd52c1
Revises: 1663d24b4c12
Create Date: 2024-06-23 18:14:01.504593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa983cd52c1'
down_revision = '1663d24b4c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_deal_stages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('hubspot_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'student_id'),
    sa.UniqueConstraint('hubspot_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_deal_stages')
    # ### end Alembic commands ###
