"""empty message

Revision ID: 4b3e6108c2c5
Revises: 9bfa98910b7c
Create Date: 2024-07-21 22:55:14.547440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3e6108c2c5'
down_revision = '9bfa98910b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_test_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('some_integer', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_test_table', schema=None) as batch_op:
        batch_op.drop_column('some_integer')

    # ### end Alembic commands ###
