"""empty message

Revision ID: 51cfc2e234d7
Revises: 5d68dd5e5d5c
Create Date: 2024-10-15 11:55:31.234955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51cfc2e234d7'
down_revision = '5d68dd5e5d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_fb_ads_insight_report_basic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_rivery_run_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_fb_ads_insight_report_basic', schema=None) as batch_op:
        batch_op.drop_column('_rivery_run_id')

    # ### end Alembic commands ###
