"""empty message

Revision ID: 5bad2cdd604d
Revises: 9fe9821795f3
Create Date: 2024-07-01 14:36:19.236499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bad2cdd604d'
down_revision = '9fe9821795f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schoolmaster_id', sa.String(), nullable=True))
        batch_op.drop_column('school_master_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_master_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('schoolmaster_id')

    # ### end Alembic commands ###
