"""empty message

Revision ID: 5c793c104c45
Revises: a7a5d1062638
Create Date: 2024-06-27 00:11:02.177305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c793c104c45'
down_revision = 'a7a5d1062638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csv_hubspot_id', sa.String(), nullable=True))
        batch_op.drop_column('csa_fullname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csa_fullname', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('csv_hubspot_id')

    # ### end Alembic commands ###
