"""empty message

Revision ID: 625eef28a3d8
Revises: d537e21d15ee
Create Date: 2024-06-04 01:24:26.377501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625eef28a3d8'
down_revision = 'd537e21d15ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_firstname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('student_lastname', sa.String(), nullable=False))

    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('drive_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('drive_url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.drop_column('student_lastname')
        batch_op.drop_column('student_firstname')

    # ### end Alembic commands ###
