"""empty message

Revision ID: 671112d13228
Revises: 462f23a702e3
Create Date: 2024-07-29 12:13:16.910905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671112d13228'
down_revision = '462f23a702e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__86740b5d')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__4fc7b804')

    with op.batch_alter_table('student_new_payment', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index('idx_rivery__0ba5e805')

    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__3fb4cc72')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__3fb4cc72', ['date'], unique=False)

    with op.batch_alter_table('student_new_payment', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__0ba5e805', ['id', 'hubspot_id'], unique=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__4fc7b804', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__86740b5d', ['hubspot_id', 'type_of_collection_code', 'created_at'], unique=False)

    # ### end Alembic commands ###
