"""empty message

Revision ID: 6dfd2cb8bef9
Revises: 912a2eb30746
Create Date: 2024-07-21 19:21:34.000473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dfd2cb8bef9'
down_revision = '912a2eb30746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_first_payment')
    with op.batch_alter_table('new_test_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('some_float', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_test_table', schema=None) as batch_op:
        batch_op.drop_column('some_float')

    op.create_table('student_first_payment',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hubspot_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_of_collection', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='student_first_payment_pkey')
    )
    # ### end Alembic commands ###
