"""empty message

Revision ID: 72d90ca1e0ea
Revises: 6d42a7c70340
Create Date: 2024-09-19 08:59:13.931720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d90ca1e0ea'
down_revision = '6d42a7c70340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bg_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_job_ready', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_job_ready_tmp')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__fe7acb13')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__fe7acb13', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('bg_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_job_ready_tmp', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_job_ready')

    # ### end Alembic commands ###
