"""empty message

Revision ID: 7715ae76d0e0
Revises: 7df2a128d577
Create Date: 2024-06-05 08:43:17.600519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7715ae76d0e0'
down_revision = '7df2a128d577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_success_advisors', schema=None) as batch_op:
        batch_op.drop_column('csa_hs_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_success_advisors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csa_hs_id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
