"""empty message

Revision ID: 7de2986e2990
Revises: 8bcd370fa5f2
Create Date: 2024-10-26 11:38:45.000654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de2986e2990'
down_revision = '8bcd370fa5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bg_student_changes_2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_modified', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bg_student_changes_2', schema=None) as batch_op:
        batch_op.drop_column('object_modified')

    # ### end Alembic commands ###
