"""empty message

Revision ID: 7df2a128d577
Revises: be3b175a1f39
Create Date: 2024-06-05 01:23:50.498428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df2a128d577'
down_revision = 'be3b175a1f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.alter_column('school_master_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.alter_column('school_master_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
