"""empty message

Revision ID: 7f3a68eb72ef
Revises: 284ff962881b
Create Date: 2024-07-18 15:15:40.398973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f3a68eb72ef'
down_revision = '284ff962881b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp_student_applications_b42')
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_program', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.drop_column('current_program')

    op.create_table('tmp_student_applications_b42',
    sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('student_applied', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('student_response_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
