"""empty message

Revision ID: 817dc85ccdee
Revises: 3848b2a9a4bb
Create Date: 2024-08-10 22:12:21.925608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '817dc85ccdee'
down_revision = '3848b2a9a4bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_ads_account_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__c4d71509')

    op.drop_table('google_ads_account_performance_by_hour')
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__8af7db42')

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.alter_column('adgroup_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('idx_rivery__4d0d8e87')

    with op.batch_alter_table('google_ads_ad_group_performance_by_hour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics_allconversions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('metrics_allconversionsvalue', sa.Float(), nullable=True))
        batch_op.alter_column('customer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('idx_rivery__73f168c0')
        batch_op.drop_column('metrics_conversions')
        batch_op.drop_column('metrics_conversionsvalue')
        batch_op.drop_column('adgroup_id')
        batch_op.drop_column('campaign_id')
        batch_op.drop_column('campaign_name')
        batch_op.drop_column('adgroup_name')

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.alter_column('adgroupad_ad_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('idx_rivery__8b29ce28')

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.alter_column('adgroupcriterion_criterionid',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('idx_rivery__27188e7b')

    with op.batch_alter_table('google_ads_campaign_performance_by_day', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('idx_rivery__a4435c57')

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('idx_rivery__fe180ed1')

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.alter_column('adgroup_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('idx_rivery__878b08c1')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__08dcd190')

    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__6245b277')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__6245b277', ['date'], unique=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__08dcd190', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__878b08c1', ['adgroup_id', 'keywordview_resourcename', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)
        batch_op.alter_column('adgroup_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__fe180ed1', ['campaign_id', 'segments_date', 'segments_device', 'segments_hour'], unique=False)
        batch_op.alter_column('campaign_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('google_ads_campaign_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__a4435c57', ['campaign_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)
        batch_op.alter_column('campaign_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__27188e7b', ['adgroupcriterion_criterionid', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)
        batch_op.alter_column('adgroupcriterion_criterionid',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__8b29ce28', ['adgroupad_ad_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)
        batch_op.alter_column('adgroupad_ad_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('google_ads_ad_group_performance_by_hour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adgroup_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adgroup_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('metrics_conversionsvalue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('metrics_conversions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_index('idx_rivery__73f168c0', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device', 'segments_hour'], unique=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('metrics_allconversionsvalue')
        batch_op.drop_column('metrics_allconversions')

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__4d0d8e87', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)
        batch_op.alter_column('adgroup_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__8af7db42', ['hubspot_id'], unique=False)

    op.create_table('google_ads_account_performance_by_hour',
    sa.Column('customer_currencycode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_descriptivename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_activeviewimpressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metrics_activeviewmeasurability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metrics_activeviewmeasurablecostmicros', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metrics_activeviewmeasurableimpressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metrics_activeviewviewability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metrics_allconversions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metrics_allconversionsvalue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metrics_clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metrics_costmicros', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metrics_impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metrics_interactioneventtypes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metrics_interactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metrics_viewthroughconversions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('segments_adnetworktype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('segments_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('segments_device', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('segments_hour', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    with op.batch_alter_table('google_ads_account_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__c4d71509', ['customer_id', 'segments_adnetworktype', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    # ### end Alembic commands ###
