"""empty message

Revision ID: 86cca2aab3c5
Revises: c9b8756abb45
Create Date: 2024-09-26 18:12:39.967422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cca2aab3c5'
down_revision = 'c9b8756abb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facebook_fb_ads_campaigns', schema=None) as batch_op:
        batch_op.alter_column('_campaign_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('facebook_fb_ads_insight_report_basic', schema=None) as batch_op:
        batch_op.alter_column('_ad_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__56da1b4b')

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__90129a40')

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__d150f9a8')

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__b3b1608a')

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__abaecb1c')

    with op.batch_alter_table('marketing_mql_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lp_variant', sa.String(), nullable=True))

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__5550848f')

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__5c9c6d7d')

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__5cc58890')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__5cc58890', ['campaign_id'], unique=False)

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__5c9c6d7d', ['dimensions_stat_time_day', 'dimensions_campaign_id'], unique=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__5550848f', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('marketing_mql_students', schema=None) as batch_op:
        batch_op.drop_column('lp_variant')

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__abaecb1c', ['id', 'created_at', 'updated_at'], unique=False)

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__b3b1608a', ['adgroup_id', 'keywordview_resourcename', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__d150f9a8', ['campaign_id', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__90129a40', ['adgroupcriterion_criterionid', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__56da1b4b', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('facebook_fb_ads_insight_report_basic', schema=None) as batch_op:
        batch_op.alter_column('_ad_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('facebook_fb_ads_campaigns', schema=None) as batch_op:
        batch_op.alter_column('_campaign_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
