"""empty message

Revision ID: 8bcd370fa5f2
Revises: f353b5dd20a1
Create Date: 2024-10-26 11:08:12.839460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcd370fa5f2'
down_revision = 'f353b5dd20a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__ff4f4eb8')

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__38e8aeb0')

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__86215c03')

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__4435b900')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__e85b6738')

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__11821327')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__11821327', ['campaign_id'], unique=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__e85b6738', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__4435b900', ['id', 'created_at', 'updated_at'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__86215c03', ['campaign_id', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__38e8aeb0', ['adgroupad_ad_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__ff4f4eb8', ['hubspot_id'], unique=False)

    # ### end Alembic commands ###
