"""empty message

Revision ID: 8efb99a510e8
Revises: 93a831a76037
Create Date: 2024-07-01 12:29:42.480195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efb99a510e8'
down_revision = '93a831a76037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_owner_changes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_hubspot_id', sa.String(), nullable=False),
    sa.Column('student_hubspot_owner_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mock_interviews', schema=None) as batch_op:
        batch_op.drop_constraint('mock_interviews_mentor_id_fkey', type_='foreignkey')
        batch_op.drop_column('home_assignment_answers')
        batch_op.drop_column('home_assignment_questions')
        batch_op.drop_column('had_home_assignment')
        batch_op.drop_column('mentor_id')
        batch_op.drop_column('questions_doc_link')
        batch_op.drop_column('mock_interview_recording_link')
        batch_op.drop_column('mock_interview_feedback_id')
        batch_op.drop_column('mentor_name')

    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.drop_column('student_lastname')
        batch_op.drop_column('student_firstname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_firstname', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('student_lastname', sa.VARCHAR(), autoincrement=False, nullable=False))

    with op.batch_alter_table('mock_interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mock_interview_feedback_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mock_interview_recording_link', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('questions_doc_link', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mentor_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('had_home_assignment', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('home_assignment_questions', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('home_assignment_answers', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('mock_interviews_mentor_id_fkey', 'mentors', ['mentor_id'], ['id'])

    op.drop_table('student_owner_changes')
    # ### end Alembic commands ###
