"""empty message

Revision ID: 912a2eb30746
Revises: d377ff3e5903
Create Date: 2024-07-18 17:37:28.716060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912a2eb30746'
down_revision = 'd377ff3e5903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.alter_column('domain',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.alter_column('domain',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
