"""testing

Revision ID: 94110c006072
Revises: e7e03e829ecb
Create Date: 2024-06-16 10:37:59.830903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94110c006072'
down_revision = 'e7e03e829ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentors', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
