"""empty message

Revision ID: 94f1d784483b
Revises: 86b1bd98b6f1
Create Date: 2024-09-12 22:16:26.861018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94f1d784483b'
down_revision = '86b1bd98b6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v2_csat_intructions_mentorship', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__1fd034fa')

    op.drop_table('v2_csat_intructions_mentorship')
    op.drop_table('nps_table')
    op.drop_table('active-c-t-students-tal')
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__5bab88ce')

    with op.batch_alter_table('csat_submitted', schema=None) as batch_op:
        batch_op.alter_column('row_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('google_ads_account_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__e17725dc')

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__ff1f9813')

    with op.batch_alter_table('google_ads_ad_group_performance_by_hour', schema=None) as batch_op:
        batch_op.alter_column('metrics_conversions',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('metrics_conversionsvalue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index('idx_rivery__2c5d0356')

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__35adea54')

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__fdc54535')

    with op.batch_alter_table('google_ads_campaign_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__01c73cbf')

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__b7c7f0b7')

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__81095ada')

    with op.batch_alter_table('nps_survey_event', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__ede4d7b0')

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__fd0ed1d5')

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__3d77295b')

    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.alter_column('placement_revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('monthly_placements_revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('yearly_placements_revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('quarterly_placements_revenue',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.drop_column('cummulative_monthly_applications')
        batch_op.drop_column('yearly_cummulative_placements')
        batch_op.drop_column('quarterly_cummulative_placements')
        batch_op.drop_column('monthly_cummulative_placements')

    with op.batch_alter_table('v3_students', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_students', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_cummulative_placements', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quarterly_cummulative_placements', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('yearly_cummulative_placements', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cummulative_monthly_applications', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('quarterly_placements_revenue',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('yearly_placements_revenue',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('monthly_placements_revenue',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('placement_revenue',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__3d77295b', ['campaign_id'], unique=False)

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__fd0ed1d5', ['dimensions_stat_time_day', 'dimensions_campaign_id'], unique=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__ede4d7b0', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('nps_survey_event', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__81095ada', ['adgroup_id', 'keywordview_resourcename', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__b7c7f0b7', ['campaign_id', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__01c73cbf', ['campaign_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__fdc54535', ['adgroupcriterion_criterionid', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__35adea54', ['adgroupad_ad_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__2c5d0356', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device', 'segments_hour'], unique=False)
        batch_op.alter_column('metrics_conversionsvalue',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('metrics_conversions',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__ff1f9813', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_account_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__e17725dc', ['customer_id', 'segments_adnetworktype', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('csat_submitted', schema=None) as batch_op:
        batch_op.alter_column('row_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__5bab88ce', ['hubspot_id'], unique=False)

    op.create_table('active-c-t-students-tal',
    sa.Column('Program', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Cohort Date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Contact ID', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Enrollment ID', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('nps_table',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pulse_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('hubspot_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('poc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_of_score', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'pulse_date', 'hubspot_id', name='pk_nps_table_13ccf')
    )
    op.create_table('v2_csat_intructions_mentorship',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('hubspot_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('poc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_of_score', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    with op.batch_alter_table('v2_csat_intructions_mentorship', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__1fd034fa', ['id', 'sent_at', 'hubspot_id', 'poc', 'type_of_score'], unique=False)

    # ### end Alembic commands ###
