"""empty message

Revision ID: 983118d18a95
Revises: 
Create Date: 2024-06-03 12:33:39.166315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983118d18a95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_success_advisors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('csa_hs_id', sa.Integer(), nullable=False),
    sa.Column('csa_fullname', sa.String(), nullable=False),
    sa.Column('csa_email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mentor_fullname', sa.String(), nullable=False),
    sa.Column('mentor_email', sa.String(), nullable=False),
    sa.Column('mentor_languages', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('student_firstname', sa.String(), nullable=False),
    sa.Column('student_lastname', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('job_description', sa.String(), nullable=False),
    sa.Column('drive_url', sa.String(), nullable=False),
    sa.Column('process_start_date', sa.DateTime(), nullable=False),
    sa.Column('process_end_date', sa.DateTime(), nullable=True),
    sa.Column('is_process_active', sa.Boolean(), nullable=False),
    sa.Column('is_closed_won', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_ready_students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('masterschool_id', sa.String(), nullable=False),
    sa.Column('hubspot_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('student_firstname', sa.String(), nullable=False),
    sa.Column('student_lastname', sa.String(), nullable=False),
    sa.Column('student_email', sa.String(), nullable=False),
    sa.Column('student_country', sa.String(), nullable=False),
    sa.Column('student_state', sa.String(), nullable=True),
    sa.Column('student_city', sa.String(), nullable=False),
    sa.Column('student_github_link', sa.String(), nullable=True),
    sa.Column('student_linkedin_link', sa.String(), nullable=True),
    sa.Column('student_cv_link', sa.String(), nullable=True),
    sa.Column('languages_fluency', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('jaq', sa.String(), nullable=False),
    sa.Column('school_master_name', sa.String(), nullable=False),
    sa.Column('is_employed', sa.Boolean(), nullable=False),
    sa.Column('csa_hs_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['csa_hs_id'], ['career_success_advisors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hubspot_id'),
    sa.UniqueConstraint('masterschool_id')
    )
    op.create_table('process_stage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('stage_in_funnel', sa.String(), nullable=False),
    sa.Column('type_of_stage', sa.String(), nullable=False),
    sa.Column('had_home_assignment', sa.Boolean(), nullable=False),
    sa.Column('home_assignment_questions', sa.String(), nullable=True),
    sa.Column('home_assignment_answers', sa.String(), nullable=True),
    sa.Column('is_pass', sa.String(), nullable=False),
    sa.Column('stage_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asked_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('date_asked', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['process_stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_interviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mentor_id', sa.String(), nullable=True),
    sa.Column('stage_id', sa.String(), nullable=False),
    sa.Column('mentor', sa.String(), nullable=True),
    sa.Column('mock_interview_datetime', sa.DateTime(), nullable=False),
    sa.Column('questions_doc_link', sa.String(), nullable=True),
    sa.Column('mock_interview_feedback_id', sa.String(), nullable=True),
    sa.Column('mock_interview_recording_link', sa.String(), nullable=True),
    sa.Column('student_nps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['process_stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_interview_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stage_id', sa.String(), nullable=False),
    sa.Column('mentor_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('mentor_name', sa.String(), nullable=True),
    sa.Column('gen_dem_feedback', sa.String(), nullable=True),
    sa.Column('comm_feedback', sa.String(), nullable=True),
    sa.Column('analytical_feedback', sa.String(), nullable=True),
    sa.Column('tech_feedback', sa.String(), nullable=True),
    sa.Column('homework', sa.String(), nullable=True),
    sa.Column('domain_feedback', sa.String(), nullable=True),
    sa.Column('pitch_feedback', sa.String(), nullable=True),
    sa.Column('past_project_feedback', sa.String(), nullable=True),
    sa.Column('internal_notes', sa.String(), nullable=True),
    sa.Column('overall_rating', sa.Float(), nullable=True),
    sa.Column('mentor_email', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['mock_interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mock_interview_feedback')
    op.drop_table('mock_interviews')
    op.drop_table('asked_questions')
    op.drop_table('process_stage')
    op.drop_table('job_ready_students')
    op.drop_table('processes')
    op.drop_table('mentors')
    op.drop_table('career_success_advisors')
    # ### end Alembic commands ###
