"""empty message

Revision ID: 98ddf427f60d
Revises: aaaa7235e31c
Create Date: 2024-06-13 02:27:17.402475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ddf427f60d'
down_revision = 'aaaa7235e31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('job_published_timestamp', sa.DateTime(), nullable=False),
    sa.Column('job_offered_to_student_timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_applied', sa.Boolean(), nullable=True),
    sa.Column('student_response_timestamp', sa.DateTime(), nullable=True),
    sa.Column('no_apply_reason', sa.String(), nullable=True),
    sa.Column('student_location_search', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_applications')
    # ### end Alembic commands ###
