"""adding smart matcher notifications אם חםנ רקשגט אשנךק

Revision ID: 9943937e0fae
Revises: 94110c006072
Create Date: 2024-06-16 10:49:44.701721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9943937e0fae'
down_revision = '94110c006072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smart_matcher_notification', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.drop_column('smart_matcher_notification')

    # ### end Alembic commands ###
