"""empty message

Revision ID: 9fe9821795f3
Revises: 95433a395eac
Create Date: 2024-07-01 14:33:41.871074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe9821795f3'
down_revision = '95433a395eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_schoolmaster_changes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_hubspot_id', sa.String(), nullable=False),
    sa.Column('student_hubspot_schoolmaster_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_schoolmaster_changes')
    # ### end Alembic commands ###
