"""empty message

Revision ID: a6288b6b6b94
Revises: 88cc2f60a1e0
Create Date: 2024-07-24 10:32:11.104746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6288b6b6b94'
down_revision = '88cc2f60a1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__ee836dce')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__ee836dce', ['date'], unique=False)

    # ### end Alembic commands ###
