"""empty message

Revision ID: a687c570d207
Revises: 721e8882885a
Create Date: 2024-07-04 00:07:01.867718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a687c570d207'
down_revision = '721e8882885a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_cohort_changes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hubspot_id', sa.String(), nullable=False),
    sa.Column('student_cohort', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_cohort', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.drop_column('active_cohort')

    op.drop_table('student_cohort_changes')
    # ### end Alembic commands ###
