"""empty message

Revision ID: aaaa7235e31c
Revises: cda9804b0ce4
Create Date: 2024-06-11 00:35:15.390818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaaa7235e31c'
down_revision = 'cda9804b0ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.alter_column('languages_fluency',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.alter_column('languages_fluency',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
