"""empty message

Revision ID: ad35fa1fa7b4
Revises: c57c1c8bfaaa
Create Date: 2024-08-21 18:17:16.960990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad35fa1fa7b4'
down_revision = 'c57c1c8bfaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_auction_ads_basic_daily', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__ec2bec9c')

    op.drop_table('tiktok_auction_ads_basic_daily')
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__6d0bb5c4')

    with op.batch_alter_table('google_ads_account_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__a5318035')

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__f0e4332e')

    with op.batch_alter_table('google_ads_ad_group_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__4d55996b')
        batch_op.drop_column('campaign_name')
        batch_op.drop_column('metrics_conversions')
        batch_op.drop_column('adgroup_name')
        batch_op.drop_column('adgroup_id')
        batch_op.drop_column('campaign_id')
        batch_op.drop_column('metrics_conversionsvalue')

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__4a0f4a52')

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__be4d6d26')

    with op.batch_alter_table('google_ads_campaign_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__acc2c446')

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__387258c1')

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__5f2648bf')

    with op.batch_alter_table('intercom_report_contacts', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__a37d5a15')

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__eb9373c9')

    with op.batch_alter_table('marketing_mql_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_sql_entered', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_bg_enrolled_entered', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_submitted_typeform_entered', sa.DateTime(), nullable=True))

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__a0bedc49')

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.alter_column('dimensions_campaign_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('idx_rivery__1978702d')

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__45ee693e')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__45ee693e', ['date'], unique=False)

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__1978702d', ['dimensions_stat_time_day', 'dimensions_campaign_id'], unique=False)
        batch_op.alter_column('dimensions_campaign_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__a0bedc49', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('marketing_mql_students', schema=None) as batch_op:
        batch_op.drop_column('date_submitted_typeform_entered')
        batch_op.drop_column('date_bg_enrolled_entered')
        batch_op.drop_column('date_sql_entered')

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__eb9373c9', ['id', 'created_at', 'updated_at'], unique=False)

    with op.batch_alter_table('intercom_report_contacts', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__a37d5a15', ['id'], unique=False)

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__5f2648bf', ['adgroup_id', 'keywordview_resourcename', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__387258c1', ['campaign_id', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__acc2c446', ['campaign_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__be4d6d26', ['adgroupcriterion_criterionid', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__4a0f4a52', ['adgroupad_ad_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_hour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics_conversionsvalue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adgroup_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adgroup_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('metrics_conversions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_index('idx_rivery__4d55996b', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__f0e4332e', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_account_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__a5318035', ['customer_id', 'segments_adnetworktype', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__6d0bb5c4', ['hubspot_id'], unique=False)

    op.create_table('tiktok_auction_ads_basic_daily',
    sa.Column('metrics_cost_per_conversion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_real_time_conversion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_cpc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_video_play_actions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_conversion_rate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_video_views_p75', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_video_views_p50', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_impressions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_real_time_cost_per_result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_conversion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_real_time_result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_video_views_p100', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_shares', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_real_time_conversion_rate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_cost_per_secondary_goal_result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_secondary_goal_result_rate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_clicks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_cost_per_1000_reached', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_video_views_p25', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_reach', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_real_time_cost_per_conversion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_average_video_play', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_profile_visits', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_cpm', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_ctr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_video_watched_2s', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_result_rate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_video_watched_6s', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_secondary_goal_result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_cost_per_result', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_average_video_play_per_user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_real_time_result_rate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_spend', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_likes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dimensions_stat_time_day', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dimensions_ad_id', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    with op.batch_alter_table('tiktok_auction_ads_basic_daily', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__ec2bec9c', ['dimensions_stat_time_day', 'dimensions_ad_id'], unique=False)

    # ### end Alembic commands ###
