"""empty message

Revision ID: bc09ef45a378
Revises: 8efb99a510e8
Create Date: 2024-07-01 12:51:05.597763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc09ef45a378'
down_revision = '8efb99a510e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mock_interview_feedback')
    op.drop_table('mentors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentors',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mentor_fullname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mentor_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mentor_languages', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mentors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('mock_interview_feedback',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stage_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mentor_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mentor_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gen_dem_feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comm_feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('analytical_feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tech_feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('homework', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('domain_feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pitch_feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('past_project_feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('internal_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overall_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mentor_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], name='mock_interview_feedback_mentor_id_fkey'),
    sa.ForeignKeyConstraint(['stage_id'], ['mock_interviews.id'], name='mock_interview_feedback_stage_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mock_interview_feedback_pkey')
    )
    # ### end Alembic commands ###
