"""empty message

Revision ID: be3b175a1f39
Revises: 625eef28a3d8
Create Date: 2024-06-04 09:23:51.193968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3b175a1f39'
down_revision = '625eef28a3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asked_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('date_asked',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               nullable=False)

    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('mock_interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('mock_interviews', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=False))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('asked_questions', schema=None) as batch_op:
        batch_op.alter_column('date_asked',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
