"""empty message

Revision ID: c57c1c8bfaaa
Revises: 817dc85ccdee
Create Date: 2024-08-16 16:07:32.327056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57c1c8bfaaa'
down_revision = '817dc85ccdee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__1b5f4e26')

    with op.batch_alter_table('google_ads_account_performance_by_hour', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('idx_rivery__b7cf4f32')

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__b8739566')

    with op.batch_alter_table('google_ads_ad_group_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__f9082249')
        batch_op.drop_column('campaign_name')
        batch_op.drop_column('metrics_conversionsvalue')
        batch_op.drop_column('campaign_id')
        batch_op.drop_column('metrics_conversions')
        batch_op.drop_column('adgroup_id')
        batch_op.drop_column('adgroup_name')

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__37d56e1b')

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__745cf5f9')

    with op.batch_alter_table('google_ads_campaign_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__8dde4705')

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__79250d0e')

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__c4289dc6')

    with op.batch_alter_table('intercom_report_contacts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('idx_rivery__efdcff1b')

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('idx_rivery__ae920496')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__e32c7ce0')

    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__4097bd30')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__4097bd30', ['date'], unique=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__e32c7ce0', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__ae920496', ['id', 'created_at', 'updated_at'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('intercom_report_contacts', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__efdcff1b', ['id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__c4289dc6', ['adgroup_id', 'keywordview_resourcename', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__79250d0e', ['campaign_id', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__8dde4705', ['campaign_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__745cf5f9', ['adgroupcriterion_criterionid', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__37d56e1b', ['adgroupad_ad_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_hour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adgroup_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adgroup_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('metrics_conversions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('metrics_conversionsvalue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_index('idx_rivery__f9082249', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__b8739566', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_account_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__b7cf4f32', ['customer_id', 'segments_adnetworktype', 'segments_date', 'segments_device', 'segments_hour'], unique=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__1b5f4e26', ['hubspot_id'], unique=False)

    # ### end Alembic commands ###
