"""empty message

Revision ID: c5b51d551ef5
Revises: f765dcbba73c
Create Date: 2024-09-19 08:50:41.007392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b51d551ef5'
down_revision = 'f765dcbba73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bg_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_job_ready_tmp', sa.Boolean(), nullable=True))

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__b16999e5')

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__bb354386')

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__10c4dd8d')

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__e2ceba57')

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__c612fe22')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__7765bbe5')

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__8627c23c')

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__54ff34f7')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__54ff34f7', ['campaign_id'], unique=False)

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__8627c23c', ['dimensions_stat_time_day', 'dimensions_campaign_id'], unique=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__7765bbe5', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__c612fe22', ['id', 'created_at', 'updated_at'], unique=False)

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__e2ceba57', ['adgroup_id', 'keywordview_resourcename', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__10c4dd8d', ['campaign_id', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__bb354386', ['adgroupcriterion_criterionid', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__b16999e5', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('bg_students', schema=None) as batch_op:
        batch_op.drop_column('is_job_ready_tmp')

    # ### end Alembic commands ###
