"""empty message

Revision ID: c74343aa6bee
Revises: f5e5c30df91b
Create Date: 2024-07-01 21:10:15.723384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74343aa6bee'
down_revision = 'f5e5c30df91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('job_description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.alter_column('job_description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
