"""empty message

Revision ID: cda9804b0ce4
Revises: 1c56a6b9b953
Create Date: 2024-06-10 01:02:12.960854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda9804b0ce4'
down_revision = '1c56a6b9b953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mock_interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('had_home_assignment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('home_assignment_questions', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('home_assignment_answers', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mock_interviews', schema=None) as batch_op:
        batch_op.drop_column('home_assignment_answers')
        batch_op.drop_column('home_assignment_questions')
        batch_op.drop_column('had_home_assignment')
        batch_op.drop_column('stage_date')

    # ### end Alembic commands ###
