"""empty message

Revision ID: cfe75dd7b194
Revises: e6aa97d66eca
Create Date: 2024-09-03 09:27:55.501533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfe75dd7b194'
down_revision = 'e6aa97d66eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nps_table')
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__a49d54bb')

    with op.batch_alter_table('google_ads_account_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__923e7676')

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__eeaa027e')

    with op.batch_alter_table('google_ads_ad_group_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__219cbb70')
        batch_op.drop_column('campaign_id')
        batch_op.drop_column('campaign_name')
        batch_op.drop_column('adgroup_name')
        batch_op.drop_column('metrics_conversions')
        batch_op.drop_column('adgroup_id')
        batch_op.drop_column('metrics_conversionsvalue')

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__66fce93a')

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__49988ec5')

    with op.batch_alter_table('google_ads_campaign_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__0168be59')

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__628f1de0')

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__ea8eac0c')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__9b482f5d')

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__0c6d0f1f')

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__7056d52b')

    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__225a4e58')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__225a4e58', ['date'], unique=False)

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__7056d52b', ['campaign_id'], unique=False)

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__0c6d0f1f', ['dimensions_stat_time_day', 'dimensions_campaign_id'], unique=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__9b482f5d', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__ea8eac0c', ['adgroup_id', 'keywordview_resourcename', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__628f1de0', ['campaign_id', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__0168be59', ['campaign_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__49988ec5', ['adgroupcriterion_criterionid', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__66fce93a', ['adgroupad_ad_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_hour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics_conversionsvalue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adgroup_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('metrics_conversions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adgroup_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_index('idx_rivery__219cbb70', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__eeaa027e', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_account_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__923e7676', ['customer_id', 'segments_adnetworktype', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__a49d54bb', ['hubspot_id'], unique=False)

    op.create_table('nps_table',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pulse_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('hubspot_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('poc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_of_score', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'pulse_date', 'hubspot_id', name='pk_nps_table_b8bd9')
    )
    # ### end Alembic commands ###
