"""empty message

Revision ID: d05cfcb1303f
Revises: 4612b5c24654
Create Date: 2024-07-25 18:38:32.943537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd05cfcb1303f'
down_revision = '4612b5c24654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.alter_column('hubspot_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('idx_rivery__596bcf24')

    with op.batch_alter_table('new_test_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hubspot_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('type_of_collection_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.String(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('some_string')
        batch_op.drop_column('some_float')
        batch_op.drop_column('some_integer')
        batch_op.drop_column('id')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__a84f4ae3')

    with op.batch_alter_table('student_new_payment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('type_of_collection',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index('idx_rivery__9b28bf1e')

    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__2e7e5bc6')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__2e7e5bc6', ['date'], unique=False)

    with op.batch_alter_table('student_new_payment', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__9b28bf1e', ['id', 'hubspot_id'], unique=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('type_of_collection',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__a84f4ae3', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('new_test_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('some_integer', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('some_float', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('some_string', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('amount')
        batch_op.drop_column('type_of_collection_code')
        batch_op.drop_column('hubspot_id')

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__596bcf24', ['hubspot_id', 'type_of_collection_code', 'created_at'], unique=False)
        batch_op.alter_column('hubspot_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
