"""empty message

Revision ID: d377ff3e5903
Revises: 7f3a68eb72ef
Create Date: 2024-07-18 15:35:35.187144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd377ff3e5903'
down_revision = '7f3a68eb72ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.drop_constraint('job_ready_students_student_ms_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.create_unique_constraint('job_ready_students_student_ms_id_key', ['student_ms_id'])

    # ### end Alembic commands ###
