"""empty message

Revision ID: d537e21d15ee
Revises: 89ca30ce1403
Create Date: 2024-06-04 00:45:16.372575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd537e21d15ee'
down_revision = '89ca30ce1403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_address', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('email_address')

    # ### end Alembic commands ###
