"""empty message

Revision ID: d5b5112130b7
Revises: 74d3f2898965
Create Date: 2024-08-06 20:28:25.533134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b5112130b7'
down_revision = '74d3f2898965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__d3e59600')

    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.drop_column('had_home_assignment')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__55a00cd8')

    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__1bcad4cf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__1bcad4cf', ['date'], unique=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__55a00cd8', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('process_stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('had_home_assignment', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__d3e59600', ['hubspot_id'], unique=False)

    # ### end Alembic commands ###
