"""empty message

Revision ID: e6aa97d66eca
Revises: ad35fa1fa7b4
Create Date: 2024-09-02 12:42:03.123716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6aa97d66eca'
down_revision = 'ad35fa1fa7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('static_v3_students')
    op.drop_table('marinas_data')
    op.drop_table('nps_table')
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__9f9398d1')

    with op.batch_alter_table('bg_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_duration', sa.String(), nullable=True))

    with op.batch_alter_table('google_ads_account_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__34fcdb5a')

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__c115a7e1')

    with op.batch_alter_table('google_ads_ad_group_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__32232886')
        batch_op.drop_column('campaign_id')
        batch_op.drop_column('metrics_conversionsvalue')
        batch_op.drop_column('campaign_name')
        batch_op.drop_column('adgroup_name')
        batch_op.drop_column('adgroup_id')
        batch_op.drop_column('metrics_conversions')

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__a627b976')

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__0c4d6812')

    with op.batch_alter_table('google_ads_campaign_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__866473ae')

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__7386de1e')

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__caf4a4d0')

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__c2efe003')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__413534ac')

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__f1c1c81a')

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__4f9b63b8')

    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__652a82e7')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__652a82e7', ['date'], unique=False)

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__4f9b63b8', ['campaign_id'], unique=False)

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__f1c1c81a', ['dimensions_stat_time_day', 'dimensions_campaign_id'], unique=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__413534ac', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__c2efe003', ['id', 'created_at', 'updated_at'], unique=False)

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__caf4a4d0', ['adgroup_id', 'keywordview_resourcename', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__7386de1e', ['campaign_id', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__866473ae', ['campaign_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__0c4d6812', ['adgroupcriterion_criterionid', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__a627b976', ['adgroupad_ad_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_hour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metrics_conversions', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adgroup_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('adgroup_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('metrics_conversionsvalue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('campaign_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_index('idx_rivery__32232886', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__c115a7e1', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_account_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__34fcdb5a', ['customer_id', 'segments_adnetworktype', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('bg_students', schema=None) as batch_op:
        batch_op.drop_column('plan_duration')

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__9f9398d1', ['hubspot_id'], unique=False)

    op.create_table('nps_table',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pulse_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('hubspot_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('poc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_of_score', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'pulse_date', 'hubspot_id', name='pk_nps_table_fcef7')
    )
    op.create_table('marinas_data',
    sa.Column('Record ID - Contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('First Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Last Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('BG - Current cohort', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('BG - Program', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('static_v3_students',
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('form_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submission_date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_first_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_last_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('best_contact_method', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('slack_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resume_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cover_letter_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preference_company_size', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preference_sectors', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preference_location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('employment_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('past_employment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motivation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('goals', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_projects', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_projects_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('onboarding_link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('locations_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_working', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_notification', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('languages', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('past_experiences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('education', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enable_not_junior', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diversity_is_black', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diversity_is_woman', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diversity_is_latin', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subproject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('opened_a_deal', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
