"""add affiliation instead of github

Revision ID: e7e03e829ecb
Revises: b771a41945de
Create Date: 2024-06-16 10:37:25.490175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e03e829ecb'
down_revision = 'b771a41945de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_affiliation_project', sa.String(), nullable=True))
        batch_op.drop_column('student_github_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_github_link', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('student_affiliation_project')

    # ### end Alembic commands ###
