"""empty message

Revision ID: ea2dcd22a14b
Revises: 48ac1a85d996
Create Date: 2024-06-06 20:32:48.076905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2dcd22a14b'
down_revision = '48ac1a85d996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hubspot_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('hubspot_id')

    # ### end Alembic commands ###
