"""empty message

Revision ID: f36d372d6f81
Revises: 83d268cbdb89
Create Date: 2024-09-17 13:24:57.407167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f36d372d6f81'
down_revision = '83d268cbdb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp_tmp_v3_pulse_table_bfbd_ad6')
    with op.batch_alter_table('active-c-t-students-tal-1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Cohort_Date', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('Contact_ID', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('Enrollment_ID', sa.Text(), nullable=True))
        batch_op.drop_column('Cohort Date')
        batch_op.drop_column('Contact ID')
        batch_op.drop_column('Enrollment ID')

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__10e643cf')

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__57727bae')

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__89d01dfa')

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__3721b551')

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__a6b1e1ad')

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__c6c56c45')

    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_location', sa.String(), nullable=True))

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__23ba6718')

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__ccf30fc5')

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__b51b4579')

    with op.batch_alter_table('v2_ms_score', schema=None) as batch_op:
        batch_op.alter_column('row_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v2_ms_score', schema=None) as batch_op:
        batch_op.alter_column('row_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('tiktok_campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__b51b4579', ['campaign_id'], unique=False)

    with op.batch_alter_table('tiktok_auction_ads_campaign_basic_daily', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__ccf30fc5', ['dimensions_stat_time_day', 'dimensions_campaign_id'], unique=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__23ba6718', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.drop_column('plan_location')

    with op.batch_alter_table('intercom_report_conversations', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__c6c56c45', ['id', 'created_at', 'updated_at'], unique=False)

    with op.batch_alter_table('google_ads_keyword_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__a6b1e1ad', ['adgroup_id', 'keywordview_resourcename', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_campaign_performance_by_hour', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__3721b551', ['campaign_id', 'segments_date', 'segments_device', 'segments_hour'], unique=False)

    with op.batch_alter_table('google_ads_audience_performance', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__89d01dfa', ['adgroupcriterion_criterionid', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('google_ads_ad_group_performance_by_day', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__57727bae', ['adgroup_id', 'segments_adnetworktype', 'segments_date', 'segments_device'], unique=False)

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__10e643cf', ['hubspot_id'], unique=False)

    with op.batch_alter_table('active-c-t-students-tal-1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Enrollment ID', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Contact ID', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Cohort Date', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('Enrollment_ID')
        batch_op.drop_column('Contact_ID')
        batch_op.drop_column('Cohort_Date')

    op.create_table('tmp_tmp_v3_pulse_table_bfbd_ad6',
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('job_ready_students', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('active_job_searchers', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('daily_applications', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('interview_process_count', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('students_with_interview_process', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('daily_callbacks', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('this_month_callbacks', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cumulative_monthly_applications', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cvr_callback_to_applications', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('daily_placements', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('monthly_cumulative_placements', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('quarterly_cumulative_placements', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('yearly_cumulative_placements', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cvr_placement_to_callback', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('placement_revenue', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('monthly_placements_revenue', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('quarterly_placements_revenue', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('yearly_placements_revenue', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
