"""empty message

Revision ID: f41ae559073f
Revises: 6edce006d004
Create Date: 2024-08-04 21:32:53.652379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41ae559073f'
down_revision = '6edce006d004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__f344f13d')

    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('student_last_name', sa.String(), nullable=True))
        batch_op.drop_column('student_country')
        batch_op.drop_column('student_city')
        batch_op.drop_column('student_state')

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__2618c629')

    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.drop_index('idx_rivery__3a17d843')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('v3_pulse_table', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__3a17d843', ['date'], unique=False)

    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__2618c629', ['student_id', 'student_response_timestamp', 'source', 'id'], unique=False)

    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_state', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_city', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('student_country', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('student_last_name')
        batch_op.drop_column('student_first_name')

    with op.batch_alter_table('another_payments_test_1', schema=None) as batch_op:
        batch_op.create_index('idx_rivery__f344f13d', ['hubspot_id'], unique=False)

    # ### end Alembic commands ###
