"""empty message

Revision ID: f5e5c30df91b
Revises: 5bad2cdd604d
Create Date: 2024-07-01 15:32:05.380861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e5c30df91b'
down_revision = '5bad2cdd604d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.drop_column('csa_hubspot_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_ready_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csa_hubspot_id', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
