"""empty message

Revision ID: f7b7090959f0
Revises: 1fd7aac46981
Create Date: 2024-06-17 06:21:27.998996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7b7090959f0'
down_revision = '1fd7aac46981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('job_published_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_applications', schema=None) as batch_op:
        batch_op.alter_column('job_published_timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
