from db import db


class TiktokAuctionAdsCampaignBasicDaily(db.Model):
    __tablename__ = 'tiktok_auction_ads_campaign_basic_daily'

    metrics_cost_per_conversion = db.Column(db.String)
    metrics_real_time_conversion = db.Column(db.String)
    metrics_cpc = db.Column(db.String)
    metrics_video_play_actions = db.Column(db.String)
    metrics_conversion_rate = db.Column(db.String)
    metrics_video_views_p75 = db.Column(db.String)
    metrics_result = db.Column(db.String)
    metrics_video_views_p50 = db.Column(db.String)
    metrics_impressions = db.Column(db.String)
    metrics_comments = db.Column(db.String)
    metrics_real_time_cost_per_result = db.Column(db.String)
    metrics_conversion = db.Column(db.String)
    metrics_real_time_result = db.Column(db.String)
    metrics_video_views_p100 = db.Column(db.String)
    metrics_shares = db.Column(db.String)
    metrics_real_time_conversion_rate = db.Column(db.String)
    metrics_cost_per_secondary_goal_result = db.Column(db.String)
    metrics_secondary_goal_result_rate = db.Column(db.String)
    metrics_clicks = db.Column(db.String)
    metrics_cost_per_1000_reached = db.Column(db.String)
    metrics_video_views_p25 = db.Column(db.String)
    metrics_reach = db.Column(db.String)
    metrics_real_time_cost_per_conversion = db.Column(db.String)
    metrics_average_video_play = db.Column(db.String)
    metrics_profile_visits = db.Column(db.String)
    metrics_cpm = db.Column(db.String)
    metrics_ctr = db.Column(db.String)
    metrics_video_watched_2s = db.Column(db.String)
    metrics_result_rate = db.Column(db.String)
    metrics_video_watched_6s = db.Column(db.String)
    metrics_secondary_goal_result = db.Column(db.String)
    metrics_cost_per_result = db.Column(db.String)
    metrics_average_video_play_per_user = db.Column(db.String)
    metrics_real_time_result_rate = db.Column(db.String)
    metrics_spend = db.Column(db.String)
    metrics_likes = db.Column(db.String)
    dimensions_stat_time_day = db.Column(db.String)
    dimensions_campaign_id = db.Column(db.String, primary_key=True)