from db import db


class IntercomReportContacts(db.Model):
    __tablename__ = 'intercom_report_contacts'

    type = db.Column(db.String)
    id = db.Column(db.String, primary_key=True)
    workspace_id = db.Column(db.String)
    external_id = db.Column(db.String)
    role = db.Column(db.String)
    email = db.Column(db.String)
    phone = db.Column(db.String)
    name = db.Column(db.String)
    avatar = db.Column(db.String)
    owner_id = db.Column(db.String)
    social_profiles = db.Column(db.JSON)
    has_hard_bounced = db.Column(db.Boolean)
    marked_email_as_spam = db.Column(db.Boolean)
    unsubscribed_from_emails = db.Column(db.Boolean)
    created_at = db.Column(db.Integer)
    updated_at = db.Column(db.Integer)
    signed_up_at = db.Column(db.Integer)
    last_seen_at = db.Column(db.Integer)
    last_replied_at = db.Column(db.String)
    last_contacted_at = db.Column(db.String)
    last_email_opened_at = db.Column(db.String)
    last_email_clicked_at = db.Column(db.String)
    language_override = db.Column(db.String)
    browser = db.Column(db.String)
    browser_version = db.Column(db.String)
    browser_language = db.Column(db.String)
    os = db.Column(db.String)
    location = db.Column(db.JSON)
    android_app_name = db.Column(db.String)
    android_app_version = db.Column(db.String)
    android_device = db.Column(db.String)
    android_os_version = db.Column(db.String)
    android_sdk_version = db.Column(db.String)
    android_last_seen_at = db.Column(db.String)
    ios_app_name = db.Column(db.String)
    ios_app_version = db.Column(db.String)
    ios_device = db.Column(db.String)
    ios_os_version = db.Column(db.String)
    ios_sdk_version = db.Column(db.String)
    ios_last_seen_at = db.Column(db.String)
    custom_attributes = db.Column(db.JSON)
    tags = db.Column(db.JSON)
    notes = db.Column(db.JSON)
    companies = db.Column(db.JSON)
    opted_out_subscription_types = db.Column(db.JSON)
    utm_campaign = db.Column(db.String)
    utm_content = db.Column(db.String)
    utm_medium = db.Column(db.String)
    utm_source = db.Column(db.String)
    utm_term = db.Column(db.String)
    referrer = db.Column(db.String)