from db import db


class V3Students(db.Model):
    __tablename__ = 'v3_students'

    token = db.Column(db.Text)
    form_id = db.Column(db.Text)
    submission_date = db.Column(db.Text)
    domain = db.Column(db.Text)
    student_first_name = db.Column(db.Text)
    student_last_name = db.Column(db.Text)
    email_address = db.Column(db.Text)
    country = db.Column(db.Text)
    state = db.Column(db.Text)
    city = db.Column(db.Text)
    resume_url = db.Column(db.Text)
    preference_company_size = db.Column(db.Text)
    preference_sectors = db.Column(db.Text)
    preference_location = db.Column(db.Text)
    employment_state = db.Column(db.Text)
    past_employment = db.Column(db.Text)
    motivation = db.Column(db.Text)
    goals = db.Column(db.Text)
    other_projects = db.Column(db.Text)
    other_projects_text = db.Column(db.Text)
    locations_json = db.Column(db.Text)
    is_working = db.Column(db.Integer)
    email_notification = db.Column(db.Text)
    languages = db.Column(db.Text)
    past_experiences = db.Column(db.Text)
    education = db.Column(db.Text)
    skills = db.Column(db.Text)
    enable_not_junior = db.Column(db.Text)
    diversity_is_black = db.Column(db.Text)
    diversity_is_woman = db.Column(db.Text)
    diversity_is_latin = db.Column(db.Text)
    subproject = db.Column(db.Text)
    record_id = db.Column(db.String, primary_key=True)
